MedicalService/Controllers/DoctorController.cs
using System.Web.Mvc;

namespace MedicalService.Controllers
{
    public class DoctorController : Controller
    {
        // GET: Doctor
        public ActionResult MedicalRecord()
        {
            return View();
        }
    }
}

MedicalService/Controllers/PatientController.cs
using System.Web.Mvc;

namespace MedicalService.Controllers
{
    public class PatientController : Controller
    {
        [AllowAnonymous]
        // GET: DoctorsAppointment
        public ActionResult Appointment()
        {
            return View();
        }
    }
}

MedicalService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" 
          crossorigin="anonymous">
    <link href="@Url.Content("~/wwwroot/css/shared/_layout.css")" rel="stylesheet" />
    @RenderSection("stylesheets", required: false)

    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Medical Service", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("doctor"))
                        {
                            // Role doctor
                            <li>@Html.ActionLink("Patients", "MedicalRecord", "Doctor")</li>
                        }
                        else
                        {
                            if (User.IsInRole("patient"))
                            {
                                // Role patient
                                <li>@Html.ActionLink("Doctor's appointment", "Appointment", "Patient")</li>
                            }
                            else
                            {
                                // Authentificated Without role
                            }
                        }
                    }
                    else
                    {
                        // Not authentificated
                        <li>@Html.ActionLink("Patients", "MedicalRecord", "Doctor")</li>
                        <li>@Html.ActionLink("Doctor's appointment", "Appointment", "Patient")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Medical Service</p>
        </footer>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular-route.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular-resource.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.2.0/ui-bootstrap-tpls.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.0/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-moment/1.0.1/angular-moment.min.js"></script>
    <script src="@Url.Content("~/wwwroot/js/app.js")"></script>
    
    @RenderSection("scripts", required: false)
</body>
</html>